image: docker

stages:
  - build

build:build-docker:
  image: node:14.18.3
  stage: build
    - docker build -t martinwright/docker-react -f Dockerfile.dev .

build:run-docker:
  image: node:14.18.3
  stage: build
    - docker run -e CI=true martinwright/docker-react npm run test -- --coverage
