language: generic

os:
  - linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t martinwright/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martinwright/docker-react npm run test -- --coverage